### ISSUE TITLE
Crash on default run

### ISSUE THREAD

**Issue by brauliobo** [opscode-cookbooks/php#105]
```
Recipe: php::default
  * php_pear_channel[pear.php.net] action update
    
    ================================================================================
    Error executing action `update` on resource 'php_pear_channel[pear.php.net]'
    ================================================================================
    
    Errno::ENOENT
    -------------
    No such file or directory - pear channel-info pear.php.net
    
    Cookbook Trace:
    ---------------
    /home/braulio/chef-solo/cookbooks-2/php/providers/pear_channel.rb:88:in `exists?'
    /home/braulio/chef-solo/cookbooks-2/php/providers/pear_channel.rb:50:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /home/braulio/chef-solo/cookbooks-2/php/recipes/default.rb
    
     25: php_pear_channel 'pear.php.net' do
     26:   action :update
     27: end
     28: 
    
    Compiled Resource:
    ------------------
    # Declared in /home/braulio/chef-solo/cookbooks-2/php/recipes/default.rb:25:in `from_file'
    
    php_pear_channel("pear.php.net") do
      action [:update]
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name :php
      recipe_name "default"
      channel_name "pear.php.net"
    end
    
```

**Comment by Rockstar04** [comment]
The default run is currently passing basic serverspec tests on all major platforms, without more information I will have to close this.
